### ISSUE TITLE
[Question] PHP minimum version

### ISSUE THREAD

**Issue by bertrandgauthier** [stefanorg/graphql-middleware#2]
Hi,
Is 7.0 really the minimum version of PHP required, please ?
Thanks.

**Comment by stefanorg** [comment]
Hi, at the moment this is not strict. Why ?

**Comment by bertrandgauthier** [comment]
Because i'd like to give a try at your package but we use PHP 5.6 !

**Comment by stefanorg** [comment]
i think i can modify the requirements this way:
```
"php": "^5.6 || ^7.0"
```

**Comment by bertrandgauthier** [comment]
It would be great. If you don't use stuffs that are 7.0 only...

**Comment by stefanorg** [comment]
at the moment, as i remember, there is no strict php 7 requirements

**Comment by stefanorg** [comment]
Fixed php requirements. you should be good to go now.

**Comment by bertrandgauthier** [comment]
Splendid, thanks!
